from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from langchain_core.messages import HumanMessage, AIMessage
from agent_runnable import app, config
import traceback
import sys

app_fastapi = FastAPI()

# Enable CORS
app_fastapi.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Change this to your frontend domain in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"]
)

# Define input schema with field validations
class UserInput(BaseModel):
    message: str = Field(..., min_length=1, description="User message")
    patient_id: str | None = Field(None, description="Unique patient ID")
    patient_name: str | None = Field(None, description="Full name of the patient")

@app_fastapi.post("/chat")
async def chat_endpoint(user_input: UserInput):
    message = user_input.message.strip()

    if not message:
        raise HTTPException(status_code=400, detail="Message cannot be empty.")

    # Initial patient name/id collection
    if not user_input.patient_name:
        return {"response": "Hello! Please enter your full name."}
    if not user_input.patient_id:
        return {"response": f"Thanks {user_input.patient_name}, now enter your Patient ID."}

    # Define conversation state
    state = {
        "messages": [HumanMessage(content=message)],
        "patient_name": user_input.patient_name,
        "rewrite_count": 0,
        "patient_id": user_input.patient_id,
    }

    try:
        thread_id = user_input.patient_id
        config_with_thread = {"configurable": {"thread_id": thread_id}}

        events = app.stream(state, config=config_with_thread, stream_mode="values")
        response_chunks = []

        for event in events:
            if not event.get("messages"):
                continue
            last_msg = event["messages"][-1]
            if isinstance(last_msg, AIMessage):
                content = last_msg.content
                if isinstance(content, dict):
                    response_chunks.append(content.get("content", str(content)))
                elif isinstance(content, str):
                    response_chunks.append(content.strip())

        if not response_chunks:
            raise HTTPException(status_code=500, detail="No response generated by the agent.")

        response = " ".join(response_chunks).strip()
        return {"response": response}

    except Exception as e:
        traceback.print_exc(file=sys.stdout)
        raise HTTPException(status_code=500, detail=f"Agent error: {str(e)}")

@app_fastapi.get("/")
def root():
    return {"status": "Hospital agent is running."}
